name: multitask-nlp-docker-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers
      - sentence-transformers
      - scikit-learn
      - seaborn
      - matplotlib
      - pandas
      - plotly
